version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carteira-backend
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=carteira
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - db
      - jaeger
      - loki

  db:
    image: postgres:14-alpine
    container_name: carteira-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carteira
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Prometheus para coletar métricas
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app

  # Grafana para visualizar logs e métricas
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000" # Painel do Grafana acessível na porta 3001
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  # Loki para centralizar logs da aplicação
  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml

  # Jaeger para rastreamento distribuído
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686" # UI para visualizar traces
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"

volumes:
  db_data:
  grafana_data:
  loki_data:
