auth_enabled: false

server:
  http_listen_port: 3100  # Porta do Loki

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2025-02-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:  # Especificando armazenamento local
    directory: /loki/data  # Caminho para armazenar os dados

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 dias

chunk_store_config: {}

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

compactor:
  working_directory: /loki/compactor

common:
  path_prefix: /loki/data
